name: Deploy SWA (token)
on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # ← This reads your token from the GitHub Secret you created
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          action: upload
          app_location: "/"      # your index.html is at repo root
          output_location: ""    # no build folder; deploy exactly what's in app_location
          skip_app_build: true   # don't run Oryx
          api_location: ""       # using a separately linked Function App
