name: Deploy SWA (static root)
on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"      # index.html is at repo root
          output_location: ""    # no build output folder
          skip_app_build: true   # do NOT run Oryx
          api_location: ""       # we will link the Function App separately
