name: SWA Deploy (token)
on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      # Prove the secret is present (no value leaked)
      - name: ✅ Check token secret exists
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "❌ AZURE_STATIC_WEB_APPS_API_TOKEN missing/empty"; exit 1; fi
          echo "✅ Token secret present (len: $(echo -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" | wc -c))"

      # Deploy static files from repo root; no build; no API bundled
      - name: 🚀 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: ""      # upload exactly what's in app_location
          skip_app_build: true     # don't run Oryx
          api_location: ""         # you will link the Function App in the portal
