name: SWA Deploy (OIDC)
on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # REQUIRED

    steps:
      - uses: actions/checkout@v4

      - name: Get OIDC token for SWA
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('api://AzureStaticWebApps');
            core.setOutput('id_token', token);

      - name: Verify OIDC token present
        run: |
          if [ -z "${{ steps.oidc.outputs.id_token }}" ]; then
            echo "❌ OIDC token missing (check permissions.id-token: write)"; exit 1; fi
          echo "✅ OIDC token acquired (len: $(echo -n "${{ steps.oidc.outputs.id_token }}" | wc -c))"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          github_id_token: ${{ steps.oidc.outputs.id_token }}  # OIDC auth only
          action: upload
          app_location: "/"      # your index.html is at repo root
          output_location: ""    # no build folder
          skip_app_build: true
          api_location: ""       # you'll link the Function App in the portal

          github_id_token: ${{ steps.oidc.outputs.id_token }}  # OIDC auth
          action: upload
          app_location: "/"      # index.html is at repo root
          output_location: ""    # no build output folder
          skip_app_build: true
          api_location: ""       # you'll link the Function App in the portal

