name: SWA Deploy (OIDC)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Get an OIDC token (no secrets needed)
      - id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('api://AzureStaticWebApps');
            core.setOutput('token', token);

      # Single deploy step, single `with:` map (no duplicates)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          github_id_token: ${{ steps.oidc.outputs.token }}
          action: upload
          app_location: /
          output_location: ''
          skip_app_build: true
          api_location: ''

