name: Deploy SWA (OIDC)
on:
  push: { branches: [main] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Get OIDC token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: core.getIDToken()
          result-encoding: string

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          github_id_token: ${{ steps.oidc.outputs.result }}
          action: upload
          app_location: "/"
          output_location: ""     # no build output folder
          skip_app_build: true    # don’t run Oryx
          api_location: ""        # using linked Function App, not managed API
