name: Deploy Azure Static Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'style.css'
      - 'script.js'
      - 'data.js'
      - 'assets/**'
      - '.github/workflows/deploy-swa.yaml'

permissions:
  id-token: write
  contents: read

concurrency:
  group: swa-timesheets-dev
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload              # valid input
          app_location: '/'           # repo root
          api_location: ''            # no integrated API
          output_location: ''         # no build output folder
          skip_app_build: true        # do not run npm/yarn
          skip_api_build: true
          production_branch: 'main'
