name: Web + Functions (single workflow, conditional deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web }}
      api_changed: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v4

      # Detect which side changed in this commit/push
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            web:
              - 'index.html'
              - 'script.js'
              - 'data.js'
              - 'staticwebapp.config.json'
              - 'routes.json'
              - 'assets/**'
            api:
              - 'src/Timesheets.Functions/**'
              - '!src/Timesheets.Functions/**/*.md'

  deploy_web:
    needs: plan
    if: needs.plan.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # SWA deploy — static only; never build API here
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /
          skip_api_build: true
          production_branch: main

  deploy_api:
    needs: plan
    if: needs.plan.outputs.api_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Publish Functions
        working-directory: src/Timesheets.Functions
        run: |
          dotnet restore Timesheets.Functions.csproj
          dotnet publish Timesheets.Functions.csproj -c Release -o ../../publish

      # Choose ONE auth method below. Publish profile is quickest for dev.
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-timesheets-api-dev
          package: publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      # OIDC variant (disable the block above if you use this)
      # - name: Azure Login (OIDC)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: Deploy (OIDC)
      #   uses: Azure/functions-action@v1
      #   with:
      #     app-name: func-timesheets-api-dev
      #     package: publish
