name: Deploy Azure Function App (.NET Isolated)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Match your project's .NET version

      - name: Restore dependencies
        run: dotnet restore timesheets/Timesheets.FunctionApp/FunctionApp.csproj
        
      - name: Build
        run: dotnet build timesheets/Timesheets.FunctionApp/FunctionApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish timesheets/Timesheets.FunctionApp/FunctionApp.csproj --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: func-timesheets-api-dev
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

